### ISSUE TITLE
New classes

### ISSUE THREAD

**Issue by patrikjagodits** [SaerusTierialis/tModLoader_ExperienceAndClasses#110]
Please replace the x with your response in all relevant fields.

**Describe the feature that you would like**
It would be nice,if u added a class for rogue class from calamity mod. Maybe the assassin class could be changed to it,or something like this. The bard/healer from thorium mod could also be a blessing for the modded community. The healer maybe could heal ita surroundings,or if the uses a potion,the allies get the buffs aswell.

**Describe any alternatives that you have considered**
x

**Additional context**
x

**Comment by SaerusTierialis** [comment]
Rogue, symphonic, radiant, and any other custom damage types are now supported (in the latest beta - soon to be released to mod browser).
