### ISSUE TITLE
You say that you wish to move towards a stats based system? I'd perfer if it stayed like it is.

### ISSUE THREAD

**Issue by Wyrdean** [SaerusTierialis/tModLoader_ExperienceAndClasses#53]
I think that a stat based system would make it far too similar to the other Rpg mods that exist for terraria. Although a stat based system does have its advantages, it also has several detriments such as limiting any new classes that are introduced to the stats that exist. 

Although I don't know exactly how you plan on adding in these stats, it seems like it would only hinder your ability to add new features.

If you were to add the stats along with the system you have currently it'd be a possible improvement to the system, but again it depends on how it's implemented.

P.s. Thanks for the mod, it's very very awsome.

P.P.s A few of your already implemented classes need a buff. For example, the Tank could use some thorns.

**Comment by SaerusTierialis** [comment]
The stat system (now called Attributes) will exist alongside passive abilities which will grant the more unique bonuses. This will clean things up without limiting what is possible.

All classes will be rebalanced with the addition of Attributes.

Tank is very likely to receive a thorns when the time comes for its abilities.

Thanks for the feedback!
